spring.application.name=auth-service

# MongoDB Atlas Connection
spring.data.mongodb.uri=mongodb+srv://slprime82_db_user:slprime82_db_user@cluster0.rcgym1p.mongodb.net/authDB?retryWrites=true&w=majority&appName=Cluster0

# Server Port
server.port=8081

# MongoDB Debug Logging
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
spring.data.mongodb.database=authDB


# JWT Configuration
app.jwt.secret=YourSuperSecretKeyForJWTGenerationAndValidationThatIsAtLeast256Bi
app.jwt.expiration.access=3600000
app.jwt.expiration.refresh=2592000000