worker_processes  1;

events {
    worker_connections  1024;
}

http {

    server {
        listen 80;
        server_name localhost;

        # AUTH SERVICE
        location /api/auth/ {

            proxy_pass http://localhost:8081;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # TOURISM SERVICE
        location /api/tours/ {

            if ($http_authorization = "") {
                return 401 "Missing Authorization Header";
            }

            proxy_pass http://localhost:8082;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location / {
            return 200 "NGINX WORKING";
        }
    }
}