worker_processes  1;

events {
    worker_connections  1024;
}

http {

    include       mime.types;
    default_type  application/json;

    sendfile on;
    keepalive_timeout  65;

    # =========================
    # Upstream Services
    # =========================

    upstream auth_service {
        server localhost:8081;
    }

    upstream tourism_service {
        server localhost:8082;
    }

    upstream payment_service {
        server localhost:8083;
    }

    # =========================
    # API Gateway Server
    # =========================

    server {
        listen 80;
        server_name localhost;

        # =========================
        # AUTH SERVICE ROUTES
        # =========================
        location /api/auth/ {
            proxy_pass http://auth_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /api/users/ {
            proxy_pass http://auth_service;
            proxy_set_header Host $host;
            proxy_set_header Authorization $http_authorization;
        }

        location /api/tourists/ {
            proxy_pass http://auth_service;
            proxy_set_header Host $host;
            proxy_set_header Authorization $http_authorization;
            
        }

        location /api/guides {
            proxy_pass http://auth_service;
            proxy_set_header Host $host;
            proxy_set_header Authorization $http_authorization;
        }

        location /api/hotels {
            proxy_pass http://auth_service;
            proxy_set_header Host $host;
            proxy_set_header Authorization $http_authorization;
        }

        # =========================
        # TOURISM SERVICE ROUTES
        # =========================
        location /api/trips {
            proxy_pass http://tourism_service;
            proxy_set_header Authorization $http_authorization;
            proxy_set_header Host $host;
        }

        location /api/guide-bookings {
            proxy_pass http://tourism_service;
            proxy_set_header Authorization $http_authorization;
             proxy_set_header Host $host;
        }

        location /api/hotel-bookings {
            proxy_pass http://tourism_service;
            proxy_set_header Authorization $http_authorization;
             proxy_set_header Host $host;
        }

        location /api/reviews {
            proxy_pass http://tourism_service;
            proxy_set_header Authorization $http_authorization;
             proxy_set_header Host $host;
        }

        # =========================
        # PAYMENT SERVICE ROUTES
        # =========================
        location /api/payments/ {
            proxy_pass http://payment_service;
            proxy_set_header Authorization $http_authorization;
        }

        location /api/wallet/ {
            proxy_pass http://payment_service;
            proxy_set_header Authorization $http_authorization;
        }

        # =========================
        # ERROR HANDLING
        # =========================
        error_page 500 502 503 504 /50x.html;

        location = /50x.html {
            root html;
        }
    }
}