server:
  port: 8080

spring:
  application:
    name: tourist-service
  data:
    mongodb:
      uri: mongodb+srv://tourism_admin:tourism_admin_123@cluster0.ipwxbmv.mongodb.net/smart_tourist_db?appName=Cluster0
      auto-index-creation: true